name: scholar_flutter
description: Scholarship Management System
environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.12.0
  http: ^1.2.0
  file_picker: ^8.1.7
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jmcbg.jpg
    - assets/jmclogo.png
    - assets/jenn.png
