sonar.projectKey=jennlangsatabi_scholar_frontend
sonar.organization=jennlangsatabi
sonar.projectName=scholar_frontend
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**,.dart_tool/**,android/**,ios/**,linux/**,macos/**,windows/**
