sonar.projectKey=VHIANCEERICH_scholar_frontend
sonar.organization=vhianceerich
sonar.projectName=scholar_frontend
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**,.dart_tool/**,android/**,ios/**,linux/**,macos/**,windows/**
sonar.newCode.referenceBranch=main
